name: build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    build:
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [ubuntu-latest, macos-latest]

      steps:
      - uses: actions/checkout@master
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@0.3.0
