name: build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux-test:
    name: Linux Test
    runs-on: ubuntu-20.04
    steps:
    - name: Run ShellCheck
      run: |
        shellcheck dotman.sh
        shellcheck tools/install.sh
    - name: Bash Testing
      # -n : ead  commands  but  do  not  execute  them.  This may be used to check a shell script for syntax errors.  This is ignored by interactive shells.
      run : |
          bash -n dotman.sh
          sh -n tools/install.sh
  macos-test:
    name: macOS Test
    runs-on: macos-latest
    steps:
      - name: Test on Bash 3
        run: |
          bash -n dotman.sh
          sh -n tools/install.sh
          
    
