name: build
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, feature/* ]
  pull_request:
    branches: [ master ]
jobs:
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@master
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@2.0.0        
  bash:
    name: bash-matrix
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        bash: [ 
          "3.0",
          "3.1",
          "3.2",
          "4.0",
          "4.1",
          "4.2",
          "4.3",
          "4.4",
          "5.1",
          "5.2"
        ]
    steps:
      - uses: actions/checkout@master
      - name: matrix test ${{ matrix.bash }}
        uses: addnab/docker-run-action@v3
        with:
          image: bash:${{ matrix.bash }}
          options: -v ${{ github.workspace }}:/work -w /work
          run: |
            bash -n dotman.sh
            sh -n tools/install.sh          
