name: build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: ShellCheck
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@0.5.0
  bash:
    name: BashTesting
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        bash: ["3.0", "4.0", "5.0"]
        cmd: ["bash -n dotman.sh", "sh -n tools/install.sh"]
    steps:          
    - uses: actions/checkout@master
    - name: "Test ${{ matrix.cmd }} with bash ${{ matrix.bash }}"
      uses: addnab/docker-run-action@v3
      with:
        image: bash:${{ matrix.bash }}
        options: -v ${{ github.workspace }}:/test -w /test
        run: ${{ matrix.cmd }}
